/* This script is generated by BlueOcean UI - create pipeline
 * issue with BlueOcean generated script: it uses single quotes for the echo stmt.
 * need to manually modify and check-in to use double quotes so the variables show their values
 * Note: for Linux we can create a shell script for the echo line in BlueOcean instead of modify the code manually. 
 *       However shell script created this way doesn't work for Windows.
*/
pipeline {
  agent any
  stages {
    stage('stage1') {
      steps {
        echo "The build number is $BUILD_NUMBER of demo $DEMO"
      }
    }

  }
  environment {
    DEMO = '1'
  }
}
